### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by olgaklimenko** [kolodnikovm/django#9]
Нужно навести порядок в структуре проекта, файлы с сеттингами в нескольких местах проекта, и не понятно какие из них нужные)

**Comment by kolodnikovm** [comment]
Я использовал django-split-settings, пожтому они разбиты на модули. Или имелся в виду одинокий settings.py вне appdir'a?)

**Comment by olgaklimenko** [comment]
Да, имелся ввиду тот файл который не в директории приложения. Если он не нужен, не надо его в репозитории хранить
